### ISSUE TITLE
NoSuchMethodError: org.apache.spark.scheduler.SparkListenerExecutorMetricsUpdate.executorUpdates()

### ISSUE THREAD

**Issue by mlcoop** [LucaCanali/sparkMeasure#48]
Trying to use sparkMeasure in scala spark application.
Get this error:
```ERROR util.Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: org.apache.spark.scheduler.SparkListenerExecutorMetricsUpdate.executorUpdates()Lscala/collection/Map;```
scalaVersion:2.12.13
sparkVersion: 2.4.6.0
sparkMeasure: 0.22

**Comment by LucaCanali** [comment]
Hi,
For Spark 2.4.6 you would need to use sparkMeasure v 0.19 (latest version of sparkMEasure that works with Spark 2.4).
sparkMeasure 0.22 only works with Spark 3.x.

**Comment by mlcoop** [comment]
@LucaCanali thanks for quick response. I changed sparkMeasures version to 0.19. Now I have another error:
`java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
	at java.lang.ClassLoader.defineClass1(Native Method)`
This should be related to sparkMeasure

**Comment by mlcoop** [comment]
is there difference in sparkMeasure implementation while using in cluster ?

**Comment by mlcoop** [comment]
I am also using `hadoop-> "3.2.0"`, is it compatible with 0.19 version ? because i started getting errors like `java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator`

**Comment by mlcoop** [comment]
Apparently it does, so i changed to 0.17 which seems to be working

**Comment by LucaCanali** [comment]
Good to hear this is working for you.
